import { useStat } from "@/stores/stat";
import { useUser } from "@/stores/user";
import { useCustomer } from "@/stores/customer";
import { usePayment } from "@/stores/payment";
import { useReminder } from "@/stores/reminder";
import { useGroup } from "@/stores/group";
import { useTemplate } from "@/stores/template";
import { useWhatsapp } from "@/stores/whatsapp";
import { useTrigger } from "@/stores/scenario/trigger";
import { useParams } from "@/stores/scenario/params";
import { useMessage } from "@/stores/scenario/message";
export const reset = () => {
  const stat = useStat();
  const user = useUser();
  const customer = useCustomer();
  const payment = usePayment();
  const reminder = useReminder();
  const group = useGroup();
  const template = useTemplate();
  const whatsapp = useWhatsapp();
  const trigger = useTrigger();
  const params = useParams();
  const message = useMessage();

  stat.$reset();
  user.$reset();
  customer.$reset();
  payment.$reset();
  reminder.$reset();
  group.$reset();
  template.$reset();
  whatsapp.$reset();
  trigger.$reset();
  params.$reset();
  message.$reset();
};
